name: jenkins-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  QA-Tests:
    runs-on: ubuntu-latest
    steps:
      # trigger jenkins by web requests, based on https://github.com/Satak/webrequest-action
      - name: Submit for QA - Addons Api Tests
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.JENKINS_GITHUB_HOST }}${{ secrets.JENKINS_GITHUB_JOB }}/buildWithParameters?token=11b5a3e31326f12fc1c30f12b6c860341c&GitRepo=$env:.GITHUB_REPOSITORY
          method: GET
          username: ${{ secrets.JENKINS_GITHUB_USER }}
          password: ${{ secrets.JENKINS_GITHUB_PASS }}