name: TriggerJenkins

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
    secrets:
      JENKINS_GITHUB_URL:
        required: true
      JENKINS_GITHUB_USER:
        required: true
      JENKINS_GITHUB_TOKEN:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Submit for Addons Api Tests
      uses: jabbukka/jenkins-trigger@main
      with:
        url: ${{ secrets.JENKINS_GITHUB_URL }}
        job_name: "GitHubAddons"
        # parameter: Job parameter in JSON format. ex) {"param1":"value1"}
        user_name: ${{ secrets.JENKINS_GITHUB_USER }}
        api_token: ${{ secrets.JENKINS_GITHUB_TOKEN }}
        wait: "true"
        timeout: "1000"
    
