name: jenkins-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      # trigger jenkins
      - name: Web Request Action
        uses: satak/webrequest-action@master
        with:
          url: https://actions.pepperi.com//job/API Testing Framework/job/Addons Api Tests/job/GitHubAddons/buildWithParameters?token=11b5a3e31326f12fc1c30f12b6c860341c&GitRepo=Addon2
          method: GET
          username: ${{ secrets.JENKINS_GITHUB_USER }}
          password: ${{ secrets.JENKINS_GITHUB_PASS }}